development:
  adapter: postgresql
  encoding: unicode
  database: panelninjademo_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: panelninjademo_test
  pool: 5
  username: myapp
  password: password1
